### ISSUE TITLE
Load balancing metric

### ISSUE THREAD

**Issue by wucke13** [covid-videoplattform/covid-videoplattform#3]
How do we want to estimate whether we need more/fewer instances?

**Comment by TheReal1604** [comment]
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-colibri.md

There is a REST Endpoint for load statistics from the jvb's. With some expirements we can better estimate when to rollout a new videobridge.

**Comment by wucke13** [comment]
Ok? Are there any insights on this topic so far?
