### ISSUE TITLE
Set appointments through Frontend

### ISSUE THREAD

**Issue by Viscosity4373** [covid-videoplattform/covid-videoplattform#4]
frontend sends http post request to daemon

daemon uses jicofo reservation api to create room
https://github.com/jitsi/jicofo/blob/master/doc/reservation.md

daemon outputs txt file with room url and time. (later pdf)

**Comment by wucke13** [comment]
How shall the request look like? Please provide a sample JSON object for a request.

Edit:
Why do we have to send a jicofo? Can't we just send a url to the user and the room is created at first person entering? Or do we want to disallow any unscheduled meetings?

**Comment by Viscosity4373** [comment]
We will do this using the django frontend. It seems that we don't need the daemon after all.

**Comment by wucke13** [comment]
Ok, I understand :)
